### ISSUE TITLE
Error: lateinit property mPlayer has not been initialized

### ISSUE THREAD

**Issue by jayharr-is** [feedfm/react-native-feed-media-audio-player#18]
Our team is using FeedFM in production in an Android React Native app alongside an error/crash reporting tool, Sentry. We've been getting a high volume of error reports, including from users, that the FeedFM player occasionally crashes the app. We have not been able to reproduce this ourselves, but we do have the error and stack trace:

`UninitializedPropertyAccessException: lateinit property mPlayer has not been initialized`

```
kotlin.UninitializedPropertyAccessException: lateinit property mPlayer has not been initialized
    at fm.feed.android.playersdk.FeedAudioPlayer.pause(FeedAudioPlayer.kt:1571)
    at fm.feed.android.playersdk.FeedAudioPlayer.stop(FeedAudioPlayer.kt:1584)
    at fm.feed.android.playersdk.FeedAudioPlayer.destroyInstance(FeedAudioPlayer.kt:1604)
    at fm.feed.android.playersdk.FeedAudioPlayer$sessionEventListener$1.sessionNotAvailable(FeedAudioPlayer.kt:638)
    at fm.feed.android.playersdk.FeedSession$requestSession$1.onError(FeedSession.kt:419)
    at fm.feed.android.playersdk.FeedSession$sendRequest$1.onFailure(FeedSession.kt:264)
    at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onFailure$1$DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:96)
    at retrofit2.-$$Lambda$DefaultCallAdapterFactory$ExecutorCallbackCall$1$7JZMXmGMmuA6QMd5UmiN1rIhtW0.run
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7700)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
```

Any idea what's going on here? I wish I had better info or a reproducible test case, but no luck so far. It may be something that happens under poor network conditions? Let me know if there's any info about our setup that would be helpful.

Thanks for your help!

**Comment by arvkmr** [comment]
@jayharr-is Could you tell me which version of the react-native SDK you are using?

**Comment by eric-purrington** [comment]
@arvkmr Jay and I are working on the same team. We are using `"react-native": "~0.62.2", "react-native-feed-media-audio-player": "^3.3.6"`. Most commonly this error crashes the app after about 6 minutes or so of listening.
